#MODULE

In [2]:
import fibo

print(fib(4))

NameError: name 'null' is not defined

In [7]:
import testm


print(sum(3,4))

TypeError: 'int' object is not iterable

In [11]:
import fib2

fib1(4)

NameError: name 'fib1' is not defined

In [12]:
import numpy
numpy.__version__

'1.26.4'

In [1]:
import numpy as np
np.__version__

'2.1.0'

In [3]:
my_arr=np.array([2,4,8,16])  #numpy only deals with array
print(my_arr)
print(type(my_arr))

[ 2  4  8 16]
<class 'numpy.ndarray'>


In [5]:
my_array=np.array([2,3.4,5.6,2])  # array only stores one data type, it change the the datatype to a higher form
print(my_array)

[2.  3.4 5.6 2. ]


In [12]:
my_arr1=np.array([2.3,3.4,3,2],dtype='int16') #dtype to change datatype to specific datatype
my_arr1[0]

np.int16(2)

In [9]:
np.array([
    [2,3,4],
     [5,6,7],
    [8,9,0]
])

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 0]])

In [15]:
np.ones((3,5,2), dtype=float)  # 3 array with 5 rows and 2 columns

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [16]:
np.arange(1,31,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [17]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [4]:
np.random.random((3,3))

array([[0.44400327, 0.6097316 , 0.58270074],
       [0.88366705, 0.92444078, 0.88764456],
       [0.88570952, 0.32461133, 0.69857718]])

In [3]:
np.random.random((3,3))

array([[0.09214822, 0.63285716, 0.70270209],
       [0.42061875, 0.57900146, 0.96906479],
       [0.75914323, 0.92962212, 0.47635168]])

In [1]:
import numpy as np

np.random.randint(0,10,(3,3))

array([[3, 8, 2],
       [6, 1, 3],
       [1, 8, 8]])