In [7]:
import numpy as np

np.random.seed(0) #seed fixes the random number that has been generated.

x1=np.random.randint(10, size=6)

x2=np.random.randint(10, size=(4,3))

x3=np.random.randint(10, size=(2,3,4))

x1

array([5, 0, 3, 3, 7, 9])

In [10]:
#ndim shows the array dimention
print(x1.ndim)

print(x2.ndim)

print(x3.ndim)

1
2
3


In [13]:
#shape: shows the no. of rows and columns

print(x1.shape)

print(x2.shape)

print(x3.shape)

(6,)
(4, 3)
(2, 3, 4)


In [15]:
#size: shows the number of eleents
print(x1.size)

print(x2.size)

print(x3.size)

6
12
24


In [18]:
x1.dtype
x2.dtype  #checks the data type of variabel #once created with the 'np' suffix the variabele is associated with the numpy library

dtype('int32')

In [19]:
print("x1. itemsize=", x1.itemsize)

print("x1. itembyte=", x1.nbytes)

x1. itemsize= 4
x1. itembyte= 24


In [20]:
print(x1[3])

3


In [21]:
print(x3)

[[[8 1 5 9]
  [8 9 4 3]
  [0 3 5 0]]

 [[2 3 8 1]
  [3 3 3 7]
  [0 1 9 9]]]


In [22]:
print(x2)

[[3 5 2]
 [4 7 6]
 [8 8 1]
 [6 7 7]]


In [24]:
print(x2[2,1])

8


In [27]:
print(x3[1,1])

[3 3 3 7]


In [28]:
print(x2[0,0])

3


In [29]:
print(x2[2,-1])

1


In [30]:
x2[1,2]=33
print(x2)

[[ 3  5  2]
 [ 4  7 33]
 [ 8  8  1]
 [ 6  7  7]]


In [32]:
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
print("x[7:3:-1]= ",x[7:3:-1])  #-1 gives reverse order

x[7:3:-1]=  [7 6 5 4]


In [36]:
print(x2)

[[ 3  5  2]
 [ 4  7 33]
 [ 8  8  1]
 [ 6  7  7]]


In [37]:
print(x2[:3,:2])

[[3 5]
 [4 7]
 [8 8]]


In [42]:
print(x2[::2,::2])

[[3 2]
 [8 1]]


In [43]:
print(x2[:,1])

[5 7 8 7]


In [44]:
#RESHAPING ARRAY
#While reshaping the data to be reshaped must the size of the new array

In [50]:
z=np.arange(1,10)

z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
print(z.ndim)

1


In [52]:
y=z.reshape((3,3))

print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
print(y.ndim)

2


In [54]:
x=z.reshape(4,4)

ValueError: cannot reshape array of size 9 into shape (4,4)

In [55]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.array([7,8,9])

np.concatenate([x,y])



array([1, 2, 3, 4, 5, 6])

In [56]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr2d=np.array([
                [2,3,4],
               [5,6,7]
                ])

np.concatenate([arr2d,arr2d]) #by default the concatinate method adds rows


array([[2, 3, 4],
       [5, 6, 7],
       [2, 3, 4],
       [5, 6, 7]])

In [61]:
np.concatenate([arr2d,arr2d],axis=1) # need to define "axis" value to show where to add while joining arrays

array([[2, 3, 4, 2, 3, 4],
       [5, 6, 7, 5, 6, 7]])

In [62]:
np.vstack([x,arr2d])

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [63]:
np.hstack([x,arr2d])


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [65]:
x=[1,2,3,99,99,3,2,1]
x1,x2,x3=np.split(x,[3,5]) #(which array to split,[where to split])

print(x1 ,x2, x3)

[1 2 3] [99 99] [3 2 1]


In [67]:
x4=np.split(x,[3,])
x4

[array([1, 2, 3]), array([99, 99,  3,  2,  1])]

In [68]:
# %timeit: shows program time 

In [70]:
#Trigonometric calculations

theta=np.linspace(0,np.pi,3)
print(theta)

[0.         1.57079633 3.14159265]


In [73]:
print("sin(theta) = ",np.sin(theta))

print("cos(theta) = ",np.cos(theta))



sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
